[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[theme]
primaryColor = "#F39C12"
backgroundColor = "#FFFFFF"
textColor = "#000000"
font = "sans serif"

[general]
title = "Your App Title"
