[server]
# This changes the title and author information
headless = true
enableCORS = false
enableXsrfProtection = true

[theme]
primaryColor = "#F39C12"
backgroundColor = "#FFFFFF"
textColor = "#000000"
font = "sans serif"

[general]
# Change the author name
title = "Your New Title"
author = "Your New Author Name"  # Change this line
